const departments = [{
    MDM_IDENTIFIER: "09",
    DEPARTMENT_NAME: "Object Collectors Item",
    DISPLAY_NAME: "OBJECT",
    SHORT_NAME: "OBJ",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "28-MAR-06",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: 10,
    DEPARTMENT_NAME: "JUNAROSE",
    DISPLAY_NAME: "JUNAROSE",
    SHORT_NAME: "JR",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "19-OCT-12",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: 11,
    DEPARTMENT_NAME: "ONLY & SONS",
    DISPLAY_NAME: "ONLY & SONS",
    SHORT_NAME: "ONS",
    BRAND_HOUSE_MDM: 1,
    DELETED: "N",
    CREATED_DATE: "30-SEP-13",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: 13,
    DEPARTMENT_NAME: "Bestseller",
    DISPLAY_NAME: "Bestseller",
    SHORT_NAME: "BES",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "25-SEP-05",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: 14,
    DEPARTMENT_NAME: "Y.A.S",
    DISPLAY_NAME: "Y.A.S",
    SHORT_NAME: "YAS",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "01-APR-14",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: 15,
    DEPARTMENT_NAME: "PRODUKT",
    DISPLAY_NAME: "PRODUKT",
    SHORT_NAME: "PKT",
    BRAND_HOUSE_MDM: null,
    DELETED: "N",
    CREATED_DATE: "25-NOV-14",
    CHANGED_DATE: "13-JUL-17"
}, {
    MDM_IDENTIFIER: 16,
    DEPARTMENT_NAME: "ADPT",
    DISPLAY_NAME: "ADPT",
    SHORT_NAME: "ADP",
    BRAND_HOUSE_MDM: null,
    DELETED: "N",
    CREATED_DATE: "20-JAN-15",
    CHANGED_DATE: "13-JUL-17"
}, {
    MDM_IDENTIFIER: 17,
    DEPARTMENT_NAME: "Female",
    DISPLAY_NAME: "Female",
    SHORT_NAME: "FFF",
    BRAND_HOUSE_MDM: null,
    DELETED: "N",
    CREATED_DATE: "03-MAR-15",
    CHANGED_DATE: "13-JUL-17"
}, {
    MDM_IDENTIFIER: 18,
    DEPARTMENT_NAME: "Noisy may",
    DISPLAY_NAME: "Noisy may",
    SHORT_NAME: "NM",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "14-DEC-16",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: 19,
    DEPARTMENT_NAME: "P O S T Y R",
    DISPLAY_NAME: "P O S T Y R",
    SHORT_NAME: "PO",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "20-SEP-17",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: 12,
    DEPARTMENT_NAME: "MAMA.LICIOUS",
    DISPLAY_NAME: "MAMA.LICIOUS",
    SHORT_NAME: "MAM",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "12-APR-11",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: "02",
    DEPARTMENT_NAME: "ONLY",
    DISPLAY_NAME: "ONLY",
    SHORT_NAME: "ON",
    BRAND_HOUSE_MDM: 1,
    DELETED: "N",
    CREATED_DATE: "01-JAN-00",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: "03",
    DEPARTMENT_NAME: "name it",
    DISPLAY_NAME: "name it",
    SHORT_NAME: "NIT",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "01-JAN-00",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: "04",
    DEPARTMENT_NAME: "Jack & Jones",
    DISPLAY_NAME: "Jack & Jones",
    SHORT_NAME: "JJ",
    BRAND_HOUSE_MDM: 2,
    DELETED: "N",
    CREATED_DATE: "01-JAN-00",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: "05",
    DEPARTMENT_NAME: "Vero Moda",
    DISPLAY_NAME: "Vero Moda",
    SHORT_NAME: "VM",
    BRAND_HOUSE_MDM: 4,
    DELETED: "N",
    CREATED_DATE: "01-JAN-00",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: "07",
    DEPARTMENT_NAME: "Selected",
    DISPLAY_NAME: "Selected",
    SHORT_NAME: "SEL",
    BRAND_HOUSE_MDM: 2,
    DELETED: "N",
    CREATED_DATE: "01-JAN-00",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: "06",
    DEPARTMENT_NAME: "OUTFITTERS NATION",
    DISPLAY_NAME: "OUTFITTERS NATION",
    SHORT_NAME: "OU",
    BRAND_HOUSE_MDM: null,
    DELETED: "N",
    CREATED_DATE: "12-FEB-07",
    CHANGED_DATE: "13-JUL-17"
}, {
    MDM_IDENTIFIER: "08",
    DEPARTMENT_NAME: "Pieces",
    DISPLAY_NAME: "Pieces",
    SHORT_NAME: "ACC",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "01-JAN-00",
    CHANGED_DATE: "14-MAR-18"
}, {
    MDM_IDENTIFIER: "01",
    DEPARTMENT_NAME: "VILA",
    DISPLAY_NAME: "VILA",
    SHORT_NAME: "VILA",
    BRAND_HOUSE_MDM: 3,
    DELETED: "N",
    CREATED_DATE: "01-JAN-00",
    CHANGED_DATE: "14-MAR-18"
}];

module.exports = departments;