const brands =
    [{
        MDM_IDENTIFIER: "0801",
        BRAND_NAME: "Pieces",
        BRAND_NAME_SHORT: "PI",
        DEPARTMENT_MDM: "08",
        CREATED_DATE: "01-JUN-04",
        CHANGED_DATE: "03-SEP-13",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0201",
        BRAND_NAME: "ONLY",
        BRAND_NAME_SHORT: "ON",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "17-FEB-04",
        CHANGED_DATE: "03-SEP-13",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0501",
        BRAND_NAME: "Vero Moda",
        BRAND_NAME_SHORT: "VM",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "17-FEB-04",
        CHANGED_DATE: "03-SEP-13",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0401",
        BRAND_NAME: "JACK&JONES ORIGINALS",
        BRAND_NAME_SHORT: "JI",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "17-FEB-04",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0702",
        BRAND_NAME: "Selected Homme Black",
        BRAND_NAME_SHORT: "SE",
        DEPARTMENT_MDM: "07",
        CREATED_DATE: "17-FEB-04",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0101",
        BRAND_NAME: "VILA",
        BRAND_NAME_SHORT: "VA",
        DEPARTMENT_MDM: "01",
        CREATED_DATE: "17-FEB-04",
        CHANGED_DATE: "26-OCT-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1301,
        BRAND_NAME: "Bestseller",
        BRAND_NAME_SHORT: "BES",
        DEPARTMENT_MDM: 13,
        CREATED_DATE: "17-FEB-04",
        CHANGED_DATE: "06-APR-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0901",
        BRAND_NAME: "Object Collectors Item",
        BRAND_NAME_SHORT: "OB",
        DEPARTMENT_MDM: "09",
        CREATED_DATE: "07-APR-06",
        CHANGED_DATE: "03-SEP-13",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0601",
        BRAND_NAME: "Outfitters Nation",
        BRAND_NAME_SHORT: "OF",
        DEPARTMENT_MDM: "06",
        CREATED_DATE: "12-FEB-07",
        CHANGED_DATE: "13-OCT-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0701",
        BRAND_NAME: "Selected Femme Black",
        BRAND_NAME_SHORT: "SF",
        DEPARTMENT_MDM: "07",
        CREATED_DATE: "31-AUG-07",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0302",
        BRAND_NAME: "name it kids",
        BRAND_NAME_SHORT: "NK",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "13-SEP-07",
        CHANGED_DATE: "03-SEP-18",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0303",
        BRAND_NAME: "name it mini",
        BRAND_NAME_SHORT: "NM",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "13-SEP-07",
        CHANGED_DATE: "03-SEP-18",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0304",
        BRAND_NAME: "name it newborn",
        BRAND_NAME_SHORT: "NN",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "13-SEP-07",
        CHANGED_DATE: "03-SEP-18",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0404",
        BRAND_NAME: "JACK&JONES VINTAGE",
        BRAND_NAME_SHORT: "PV",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "20-FEB-08",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0402",
        BRAND_NAME: "JACK&JONES PREMIUM",
        BRAND_NAME_SHORT: "PC",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "20-FEB-08",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0504",
        BRAND_NAME: "Vero Moda Denim",
        BRAND_NAME_SHORT: "VJ",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "05-JAN-10",
        CHANGED_DATE: "29-MAY-17",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0502",
        BRAND_NAME: "Vero Moda Aware",
        BRAND_NAME_SHORT: "VB",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "05-JAN-10",
        CHANGED_DATE: "04-APR-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0505",
        BRAND_NAME: "Vero Moda Very",
        BRAND_NAME_SHORT: "VV",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "05-JAN-10",
        CHANGED_DATE: "23-OCT-15",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0403",
        BRAND_NAME: "JACK&JONES TECH",
        BRAND_NAME_SHORT: "PT",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "31-MAR-10",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0503",
        BRAND_NAME: "Vero Moda Intimates",
        BRAND_NAME_SHORT: "VI",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "05-JUL-10",
        CHANGED_DATE: "16-OCT-18",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0202",
        BRAND_NAME: "Only Play",
        BRAND_NAME_SHORT: "PL",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "29-SEP-10",
        CHANGED_DATE: "12-NOV-13",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0412",
        BRAND_NAME: "JACK&JONES ESSENTIALS",
        BRAND_NAME_SHORT: "ESS",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "09-AUG-17",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1406,
        BRAND_NAME: "SWIM",
        BRAND_NAME_SHORT: "SWI",
        DEPARTMENT_MDM: 14,
        CREATED_DATE: "15-DEC-17",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1201,
        BRAND_NAME: "mama.licious",
        BRAND_NAME_SHORT: "ML",
        DEPARTMENT_MDM: 12,
        CREATED_DATE: "12-APR-11",
        CHANGED_DATE: "23-JUN-15",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0405",
        BRAND_NAME: "JACK&JONES CORE",
        BRAND_NAME_SHORT: "COR",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "12-APR-11",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0406",
        BRAND_NAME: "JACK&JONES FOOTWEAR",
        BRAND_NAME_SHORT: "COM",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "12-APR-11",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1202,
        BRAND_NAME: "mini mize",
        BRAND_NAME_SHORT: "MM",
        DEPARTMENT_MDM: 12,
        CREATED_DATE: "06-MAY-14",
        CHANGED_DATE: "16-OCT-18",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0407",
        BRAND_NAME: "PRODUKT",
        BRAND_NAME_SHORT: "PKT",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "24-OCT-13",
        CHANGED_DATE: "31-JUL-14",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0704",
        BRAND_NAME: "Indigo SELECTED Homme",
        BRAND_NAME_SHORT: "ISH",
        DEPARTMENT_MDM: "07",
        CREATED_DATE: "06-AUG-13",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0705",
        BRAND_NAME: "Selected",
        BRAND_NAME_SHORT: "SLD",
        DEPARTMENT_MDM: "07",
        CREATED_DATE: "04-MAR-14",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0804",
        BRAND_NAME: "Fine Pieces",
        BRAND_NAME_SHORT: "PJS",
        DEPARTMENT_MDM: "08",
        CREATED_DATE: "04-MAR-14",
        CHANGED_DATE: "08-FEB-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0805",
        BRAND_NAME: "Mini Pieces",
        BRAND_NAME_SHORT: "MIP",
        DEPARTMENT_MDM: "08",
        CREATED_DATE: "04-MAR-14",
        CHANGED_DATE: "21-SEP-15",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0414",
        BRAND_NAME: "JACK&JONES PLUS",
        BRAND_NAME_SHORT: "JJP",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "26-MAR-18",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1401,
        BRAND_NAME: "Fit to relax",
        BRAND_NAME_SHORT: "YSS",
        DEPARTMENT_MDM: 14,
        CREATED_DATE: "01-APR-14",
        CHANGED_DATE: "27-NOV-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1402,
        BRAND_NAME: "Y.A.S",
        BRAND_NAME_SHORT: "YAS",
        DEPARTMENT_MDM: 14,
        CREATED_DATE: "01-APR-14",
        CHANGED_DATE: "04-AUG-14",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1403,
        BRAND_NAME: "Simply Y.A.S",
        BRAND_NAME_SHORT: "SYS",
        DEPARTMENT_MDM: 14,
        CREATED_DATE: "01-APR-14",
        CHANGED_DATE: "27-NOV-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0210",
        BRAND_NAME: "FIRST",
        BRAND_NAME_SHORT: "FIR",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "12-OCT-16",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0306",
        BRAND_NAME: "PLAYTECH KIDS",
        BRAND_NAME_SHORT: "PTK",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "12-OCT-16",
        CHANGED_DATE: "09-NOV-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1103,
        BRAND_NAME: "ONLY & SONS",
        BRAND_NAME_SHORT: "SON",
        DEPARTMENT_MDM: 11,
        CREATED_DATE: "14-OCT-15",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0209",
        BRAND_NAME: "STUDIO",
        BRAND_NAME_SHORT: "STU",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "14-OCT-15",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0310",
        BRAND_NAME: "NAME IT MINI",
        BRAND_NAME_SHORT: "NMM",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "08-SEP-15",
        CHANGED_DATE: "27-MAY-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0706",
        BRAND_NAME: "Selected Femme White",
        BRAND_NAME_SHORT: "SFJ",
        DEPARTMENT_MDM: "07",
        CREATED_DATE: "01-APR-14",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0208",
        BRAND_NAME: "ONLY SHOES",
        BRAND_NAME_SHORT: "ONS",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "27-MAR-15",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1701,
        BRAND_NAME: "Female",
        BRAND_NAME_SHORT: "FFF",
        DEPARTMENT_MDM: 17,
        CREATED_DATE: "03-MAR-15",
        CHANGED_DATE: "14-APR-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1801,
        BRAND_NAME: "Simple stories",
        BRAND_NAME_SHORT: "SIS",
        DEPARTMENT_MDM: 18,
        CREATED_DATE: "14-DEC-16",
        CHANGED_DATE: "11-JAN-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1802,
        BRAND_NAME: "Tan lines",
        BRAND_NAME_SHORT: "TAL",
        DEPARTMENT_MDM: 18,
        CREATED_DATE: "14-DEC-16",
        CHANGED_DATE: "11-JAN-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1803,
        BRAND_NAME: "Kicks back",
        BRAND_NAME_SHORT: "KIB",
        DEPARTMENT_MDM: 18,
        CREATED_DATE: "14-DEC-16",
        CHANGED_DATE: "11-JAN-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1804,
        BRAND_NAME: "Noisy may",
        BRAND_NAME_SHORT: "NOM",
        DEPARTMENT_MDM: 18,
        CREATED_DATE: "14-DEC-16",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0511",
        BRAND_NAME: "Vero Moda Tall",
        BRAND_NAME_SHORT: "VMT",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "07-DEC-18",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0512",
        BRAND_NAME: "Vero Moda Petite",
        BRAND_NAME_SHORT: "VMP",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "07-DEC-18",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0703",
        BRAND_NAME: "Selected Homme White",
        BRAND_NAME_SHORT: "SHJ",
        DEPARTMENT_MDM: "07",
        CREATED_DATE: "11-OCT-11",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0313",
        BRAND_NAME: "NAME IT BABY",
        BRAND_NAME_SHORT: "MNB",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "10-FEB-16",
        CHANGED_DATE: "27-MAY-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1405,
        BRAND_NAME: "Studio 75",
        BRAND_NAME_SHORT: "S75",
        DEPARTMENT_MDM: 14,
        CREATED_DATE: "10-FEB-16",
        CHANGED_DATE: "27-NOV-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1602,
        BRAND_NAME: "ADPT - FEMALE",
        BRAND_NAME_SHORT: "APF",
        DEPARTMENT_MDM: 16,
        CREATED_DATE: "22-JAN-15",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0105",
        BRAND_NAME: "FIRST & I",
        BRAND_NAME_SHORT: "FII",
        DEPARTMENT_MDM: "01",
        CREATED_DATE: "05-AUG-14",
        CHANGED_DATE: "18-JUL-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0203",
        BRAND_NAME: "Blue Behaviour",
        BRAND_NAME_SHORT: "BB",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "01-NOV-11",
        CHANGED_DATE: "29-APR-14",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0206",
        BRAND_NAME: "Weekend Wardrobe",
        BRAND_NAME_SHORT: "WW",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "01-NOV-11",
        CHANGED_DATE: "29-APR-14",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0205",
        BRAND_NAME: "Fashion Favorites",
        BRAND_NAME_SHORT: "FF",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "01-NOV-11",
        CHANGED_DATE: "29-APR-14",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0204",
        BRAND_NAME: "JdY",
        BRAND_NAME_SHORT: "JdY",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "01-NOV-11",
        CHANGED_DATE: "12-NOV-13",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1001,
        BRAND_NAME: "JUNAROSE",
        BRAND_NAME_SHORT: "JR",
        DEPARTMENT_MDM: 10,
        CREATED_DATE: "19-OCT-12",
        CHANGED_DATE: "03-SEP-13",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1002,
        BRAND_NAME: "I.scenery",
        BRAND_NAME_SHORT: "ISC",
        DEPARTMENT_MDM: 10,
        CREATED_DATE: "03-FEB-15",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0411",
        BRAND_NAME: "STOCK & HANK",
        BRAND_NAME_SHORT: "JSH",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "13-FEB-17",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1502,
        BRAND_NAME: "PRODUKT",
        BRAND_NAME_SHORT: "PKT",
        DEPARTMENT_MDM: 15,
        CREATED_DATE: "04-SEP-15",
        CHANGED_DATE: "08-SEP-15",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1901,
        BRAND_NAME: "P O S T Y R",
        BRAND_NAME_SHORT: "POS",
        DEPARTMENT_MDM: 19,
        CREATED_DATE: "20-SEP-17",
        CHANGED_DATE: "20-SEP-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0802",
        BRAND_NAME: "Pieces Shoes",
        BRAND_NAME_SHORT: "PS",
        DEPARTMENT_MDM: "08",
        CREATED_DATE: "17-APR-12",
        CHANGED_DATE: "03-SEP-13",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0803",
        BRAND_NAME: "Little Pieces",
        BRAND_NAME_SHORT: "LP",
        DEPARTMENT_MDM: "08",
        CREATED_DATE: "17-APR-12",
        CHANGED_DATE: "02-JAN-18",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0104",
        BRAND_NAME: "Pure",
        BRAND_NAME_SHORT: "PUR",
        DEPARTMENT_MDM: "01",
        CREATED_DATE: "09-APR-13",
        CHANGED_DATE: "26-OCT-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0103",
        BRAND_NAME: "City",
        BRAND_NAME_SHORT: "CIT",
        DEPARTMENT_MDM: "01",
        CREATED_DATE: "09-APR-13",
        CHANGED_DATE: "26-OCT-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0102",
        BRAND_NAME: "Feminine",
        BRAND_NAME_SHORT: "FEM",
        DEPARTMENT_MDM: "01",
        CREATED_DATE: "09-APR-13",
        CHANGED_DATE: "26-OCT-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0409",
        BRAND_NAME: "JACK&JONES ACCESSORIES",
        BRAND_NAME_SHORT: "AJ",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "06-MAY-14",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0309",
        BRAND_NAME: "Little Pieces",
        BRAND_NAME_SHORT: "NLP",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "01-SEP-15",
        CHANGED_DATE: "03-SEP-18",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0211",
        BRAND_NAME: "ONLY CARMAKOMA",
        BRAND_NAME_SHORT: "OCA",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "20-SEP-17",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0410",
        BRAND_NAME: "JACK&JONES JEANS INTELLIGENCE",
        BRAND_NAME_SHORT: "INT",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "02-DEC-14",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0509",
        BRAND_NAME: "ONE FASHION",
        BRAND_NAME_SHORT: "OFA",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "07-JUL-15",
        CHANGED_DATE: "10-OCT-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0305",
        BRAND_NAME: "Name it marketing",
        BRAND_NAME_SHORT: "MN",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "03-JUN-14",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0307",
        BRAND_NAME: "lmtd kids",
        BRAND_NAME_SHORT: "LK",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "07-OCT-14",
        CHANGED_DATE: "11-MAY-16",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0308",
        BRAND_NAME: "lmtd mini",
        BRAND_NAME_SHORT: "LM",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "07-OCT-14",
        CHANGED_DATE: "11-MAY-16",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: 1101,
        BRAND_NAME: "Denim",
        BRAND_NAME_SHORT: "DNM",
        DEPARTMENT_MDM: 11,
        CREATED_DATE: "30-SEP-13",
        CHANGED_DATE: "15-OCT-15",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: 1102,
        BRAND_NAME: "Urban",
        BRAND_NAME_SHORT: "URB",
        DEPARTMENT_MDM: 11,
        CREATED_DATE: "30-SEP-13",
        CHANGED_DATE: "15-OCT-15",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0408",
        BRAND_NAME: "JACK&JONES MARKETING",
        BRAND_NAME_SHORT: "JJ",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "03-DEC-13",
        CHANGED_DATE: "28-FEB-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1501,
        BRAND_NAME: "STOCK & HANK",
        BRAND_NAME_SHORT: "SH",
        DEPARTMENT_MDM: 15,
        CREATED_DATE: "25-NOV-14",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0507",
        BRAND_NAME: "YAS",
        BRAND_NAME_SHORT: "YAS",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "05-MAR-13",
        CHANGED_DATE: "02-DEC-15",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0506",
        BRAND_NAME: "Noisy May",
        BRAND_NAME_SHORT: "NM",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "04-DEC-12",
        CHANGED_DATE: "17-OCT-18",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1404,
        BRAND_NAME: "Y.A.S Inner Secrets",
        BRAND_NAME_SHORT: "YIS",
        DEPARTMENT_MDM: 14,
        CREATED_DATE: "09-DEC-15",
        CHANGED_DATE: "27-NOV-17",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1104,
        BRAND_NAME: "TR\u00D8Y",
        BRAND_NAME_SHORT: "TMP",
        DEPARTMENT_MDM: 11,
        CREATED_DATE: "09-DEC-15",
        CHANGED_DATE: "06-JAN-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0510",
        BRAND_NAME: "Vero Moda Curve",
        BRAND_NAME_SHORT: "VMC",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "15-OCT-18",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: 1601,
        BRAND_NAME: "ADPT - MALE",
        BRAND_NAME_SHORT: "APM",
        DEPARTMENT_MDM: 16,
        CREATED_DATE: "20-JAN-15",
        CHANGED_DATE: "22-JAN-15",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0311",
        BRAND_NAME: "NAME IT KIDS",
        BRAND_NAME_SHORT: "NI",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "16-OCT-15",
        CHANGED_DATE: "27-MAY-16",
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0312",
        BRAND_NAME: "LMTD",
        BRAND_NAME_SHORT: "LT",
        DEPARTMENT_MDM: "03",
        CREATED_DATE: "16-OCT-15",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0413",
        BRAND_NAME: "JACK&JONES JUNIOR",
        BRAND_NAME_SHORT: "JJJ",
        DEPARTMENT_MDM: "04",
        CREATED_DATE: "12-MAR-18",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0207",
        BRAND_NAME: "ONLY UNITED",
        BRAND_NAME_SHORT: "UNT",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "06-NOV-12",
        CHANGED_DATE: "03-MAY-18",
        DELETED: "Y"
    }, {
        MDM_IDENTIFIER: "0212",
        BRAND_NAME: "KIDS ONLY",
        BRAND_NAME_SHORT: "KO",
        DEPARTMENT_MDM: "02",
        CREATED_DATE: "29-MAY-18",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0508",
        BRAND_NAME: "Vero Moda Shoes",
        BRAND_NAME_SHORT: "VMS",
        DEPARTMENT_MDM: "05",
        CREATED_DATE: "03-MAR-15",
        CHANGED_DATE: null,
        DELETED: "N"
    }, {
        MDM_IDENTIFIER: "0902",
        BRAND_NAME: "1.",
        BRAND_NAME_SHORT: "1.",
        DEPARTMENT_MDM: "09",
        CREATED_DATE: "04-DEC-12",
        CHANGED_DATE: "26-OCT-16",
        DELETED: "N"
    }];

module.exports = brands;
